# Carrega as variáveis do arquivo .env
export $(grep -v '^#' .env | xargs)

# Comando para inserir os dados diretamente no container MySQL
docker exec -i $CONTAINER_NAME mysql -u $MYSQLDB_USER -proot --default-character-set=utf8 $MYSQLDB_DATABASE -e "INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Biodegradável', 'Biodegradável');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Sacolas Ecológicas', 'Ecobags');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Material de Construção Ecológico', 'Material de Construção Ecológico');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Higiene Ecológica', 'Higiene Ecológica');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Bambu', 'Bambu');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Descartáveis', 'Descartáveis');
INSERT INTO db_ecoshop.tb_categorias (ativo, descricao, nome_categoria) VALUES (NULL, 'Material Orgânico', 'Material Orgânico');
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Adubo para plantas', 'Desempenha um papel fundamental no cultivo das suas plantinhas.', 7, 'https://images.petz.com.br/fotos/1613393163220.jpg', 9.99, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Escova de dente de Bambu', 'O bambu utilizado na escova é elaborado de forma responsável, com métodos sustentáveis.', 5, 'https://i.imgur.com/R0VhvJp.png', 15, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Fio dental de carvão', 'Pensado e desenvolvido para a melhor limpeza de seus dentes, o Fio Dental Ecológico de Carvão Ativado é o parceiro ideal para prevenir cáries.', 4, 'https://product-data.raiadrogasil.io/images/3490411.webp', 29.90, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Sabonete ecológico', 'Produto natural que limpa profundamente a pele, removendo impurezas e toxinas, sem agredir o meio ambiente, higiene ecológica.', 4, 'https://i.imgur.com/gXMG2LO.png', 19.99, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Pratos biodegradáveis', 'Feitos de materiais sustentáveis, são ideais para substituir pratos descartáveis tradicionais, decompondo-se naturalmente sem poluir.', 6, 'https://assets-nwrembalagens.egondola.app/v1/pro_6124_e.jpg', 45.99, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Talheres biodegradáveis', 'Alternativa sustentável aos talheres de plástico, esses utensílios se decompõem rapidamente, reduzindo o impacto ambiental.', 6, 'https://static.cdnlive.com.br/uploads/748/produto/17143982849330_thumb.jpg', 38.50, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Tinta ecológica', 'Feita com componentes naturais, essa tinta é menos tóxica e não prejudica o meio ambiente durante a produção e descarte.', 3, 'https://www.riodasostras.rj.gov.br/wp-content/uploads/2023/11/casa-de-cultura-oferece-oficina-tinta-com-terra-oficina-vai-ensinar-a-fazer-tintas-ecologicas_divulgacao.jpg', 91, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Tijolo ecológico', 'Material de construção sustentável, feito com menor consumo de recursos naturais e menor emissão de CO2, material de construção ecológico.', 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSssptQSqOH24Uh6vvqY3nY__nSPR3BDS_D_A&s', 0.85, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Churrasqueira ecológica', 'Produzida com materiais que se decompõem facilmente, essa churrasqueira é perfeita para quem busca praticidade sem prejudicar a natureza.', 1, 'https://i.imgur.com/zzufUha.png ', 35.99, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Esponja de coco', 'Uma opção natural e biodegradável para limpeza, feita a partir de fibras de coco, ideal para substituir esponjas sintéticas.', 1, 'https://m.media-amazon.com/images/I/71u3v75qPqL.__AC_SX300_SY300_QL70_ML2_.jpg', 7.50, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Utensílios de bambu', 'Feitos de bambu, material renovável e biodegradável, esses utensílios são duráveis e amigos do meio ambiente.', 5, 'https://i.imgur.com/S8PKuKz.jpeg', 39.99, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Pano de chão', 'Feito com fibras naturais e livres de produtos químicos, esse pano é uma escolha sustentável para limpeza, garantindo eficácia sem agredir o meio ambiente.', 7, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRJNgGpz1QN-siKVvN_Aroc5iTb5klzDGqvJuZ1hFbrVlZMhId2L92RAyDAUO3iy3R3jpkU_HOrV1aZKLoBdS7n8GyD2nWGZfCFOZc_xYo', 18.50, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Ecobag', 'Sacola reutilizável e ecológica, feita com materiais sustentáveis, ideal para substituir sacolas plásticas e reduzir o desperdício no dia a dia.', 2, 'https://hippieartesanatos.fbitsstatic.net/img/p/ecobag-fantasma-acredite-em-si-mesmo-128375/352089.jpg?w=675&h=900&v=202410101705', 25, 1);
INSERT INTO db_ecoshop.tb_produtos (nome_produto, descricao, categoria_id, imagem, preco, usuario_id) VALUES ('Ecobag', 'Sacola reutilizável e ecológica, feita com materiais sustentáveis, ideal para substituir sacolas plásticas e reduzir o desperdício no dia a dia.', 2, 'https://hippieartesanatos.fbitsstatic.net/img/p/ecobag-amelie-poulain-124986/344800.jpg?w=675&h=900&v=no-value', 25, 1);"